name: Delete docker images
on: 
  push
    # schedule:
    # - cron: "*/5 * * * *"

jobs:
 delete-image:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read
    #   packages: write

    steps:
      - name: Delete images
        uses: smartsquaregmbh/delete-old-packages@v0.5.0
        with: 
          token: ${{ secrets.TOKEN }}
          user: ikermenka1
          type: container
          keep: 0
          names: |
            phpfpm